### ISSUE TITLE
Possible conflict between FPSCamera and Toggle It

### ISSUE THREAD

**Issue by davelappdev** [will258012/FPSCamera-Continued#1]
## Bug Description
 If both this mod and Toggle It! are enabled, the game just exits, apparently at the end of loading the save, or very near. No message, just a silent exit. If either one is disabled (via Skyve), it loads correctly. If Toggle It! is the one not present, FPC works fine.

I thought to try disabling Toggle It! because I noticed that FPSCamera.log mentioned that it was found.

Additional information added later: it appears that it might be related to something in my Save. Any Save of this city from April 7 or earlier loads just fine. A Save I have from April 10 with some changes I made (and I don't know what they were) does exit when loading as noted above, as do all of the subsequent saves created from then. 

I don't know when the problem actually started: I noticed on April 25 that FPSCamera was not present but I don't know when it might have disappeared. Not something I use every time (but I really like when I do!)

I ended up needing to enable in Content Manager, which is not something I've needed to do since we got Skyve. That brought it back, but then I started getting the crashes/exits. I've tried the Reset buttons in FPS Camera Options. That didn't seem to help.

## Bug Reproduction
Load save file. Near the end where one would expect the UI and the game to appear, cities.exe just exits.

## Log files
[FPSCamera.log](https://github.com/will258012/CitiesSkylines-FPSCamera-Continued/files/15144128/FPSCamera.log)
[output_log.txt](https://github.com/will258012/CitiesSkylines-FPSCamera-Continued/files/15144129/output_log.txt)
Please attach the relevant part of the log file from both `.../Steam/steamapps/common/Cities_Skylines/FPSCamera.log` and `.../Cities_Skylines/Cities_Data/output_log.txt`

**Comment by will258012** [comment]
Thanks for the description! It looks like your problem occurs between version [v2.3.1](https://github.com/will258012/CitiesSkylines-FPSCamera-Continued/releases/tag/v2.3.1) and [v2.3.2](https://github.com/will258012/CitiesSkylines-FPSCamera-Continued/releases/tag/v2.3.2). Does the issue still occur if you use [v2.3.1](https://github.com/will258012/CitiesSkylines-FPSCamera-Continued/releases/tag/v2.3.1)?

**Comment by will258012** [comment]
After seeing your logs,i think the issue does not seem to be caused by this mod.

The log file suddenly stoped outputting after the save loaded while the other mods were doing something, but there is no error output. Maybe it's what you mean by the game suddenly quitting. This might be due to some other reason (such as damage or loss of assets).

You should check the integrity of the game on Steam first, if you still have the issue, feel free to add a comment.

**Comment by will258012** [comment]
Anyway, I have adjusted some code. I hope this can solve your problem.

**Comment by will258012** [comment]
Anyway, I just adjusted some codes. Hope this can solve the issue.
