### ISSUE TITLE
Game crashes in follow mode when citizen enters building

### ISSUE THREAD

**Issue by meggie-doodles** [will258012/FPSCamera-Continued#5]
## Bug Description
When viewing in first-person mode, the game crashes if the cim you are viewing enters a zoned building (house, commercial building, industry building)

## Bug Reproduction
- Either select a cim (or use the auto view and change views to a cim) who is heading home or to work
- Wait until the cim enters the building. 
- The game will crash or need to be restarted.

## Expected behavior
I expect the camera to exit out of first person view (like it does when a viewed vehicle arrives at its destination) or switch to a different viewpoint. I would rather it not crash.

## Screenshots
If applicable, add screenshots to help explain your issue.

## Log files
Please attach the relevant part of the log file from `.../Cities_Skylines/Cities_Data/output_log.txt`.

**Comment by will258012** [comment]
Hello, thanks so much for your feedback! I will look into it when I have time and fix it.

**Comment by will258012** [comment]
Hello, fixed in the latest version. This issue is closed.
